name: Deploy Chrome
on:
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  deploy:
    if: startsWith(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    env:
      CHROME_APP_ID: jfkamlikjbpcgjcdicpjaofammhfgjjh
    steps:
    - uses: actions/checkout@v4
    - run: git archive -o package.zip HEAD:src
    - uses: mikeyaworski/chrome-addon@master
      with:
        extension: ${{ env.CHROME_APP_ID }}
        zip: package.zip
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
